[package]
name = "rust_apps"
version = "0.1.0"
authors = ["Антон Владимиров <vladimirov.anton@pressindex.ru>"]
edition = "2018"

[dependencies]
memmap = "0.7.0"
page_size = "0.4.2"
log = "0.4.8"
env_logger = "0.7.1"
